/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as PrivateRouteRouteImport } from './routes/_private/route'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicStatusRouteImport } from './routes/_public/status'
import { Route as PublicCommandsRouteImport } from './routes/_public/commands'
import { Route as PrivateDashboardRouteRouteImport } from './routes/_private/dashboard/route'
import { Route as PrivateGuildRouteRouteImport } from './routes/_private/_guild/route'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as PublicAuthRedirectRouteImport } from './routes/_public/_auth/redirect'
import { Route as PublicAuthLogoutRouteImport } from './routes/_public/_auth/logout'
import { Route as PrivateDashboardOverviewRouteImport } from './routes/_private/dashboard/overview'
import { Route as PrivateGuildGuildRouteImport } from './routes/_private/_guild/guild'

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateRouteRoute = PrivateRouteRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicStatusRoute = PublicStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicCommandsRoute = PublicCommandsRouteImport.update({
  id: '/commands',
  path: '/commands',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PrivateDashboardRouteRoute = PrivateDashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateGuildRouteRoute = PrivateGuildRouteRouteImport.update({
  id: '/_guild',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicAuthRedirectRoute = PublicAuthRedirectRouteImport.update({
  id: '/_auth/redirect',
  path: '/redirect',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicAuthLogoutRoute = PublicAuthLogoutRouteImport.update({
  id: '/_auth/logout',
  path: '/logout',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PrivateDashboardOverviewRoute =
  PrivateDashboardOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => PrivateDashboardRouteRoute,
  } as any)
const PrivateGuildGuildRoute = PrivateGuildGuildRouteImport.update({
  id: '/guild',
  path: '/guild',
  getParentRoute: () => PrivateGuildRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/dashboard': typeof PrivateDashboardRouteRouteWithChildren
  '/commands': typeof PublicCommandsRoute
  '/status': typeof PublicStatusRoute
  '/guild': typeof PrivateGuildGuildRoute
  '/dashboard/overview': typeof PrivateDashboardOverviewRoute
  '/logout': typeof PublicAuthLogoutRoute
  '/redirect': typeof PublicAuthRedirectRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/dashboard': typeof PrivateDashboardRouteRouteWithChildren
  '/commands': typeof PublicCommandsRoute
  '/status': typeof PublicStatusRoute
  '/guild': typeof PrivateGuildGuildRoute
  '/dashboard/overview': typeof PrivateDashboardOverviewRoute
  '/logout': typeof PublicAuthLogoutRoute
  '/redirect': typeof PublicAuthRedirectRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_private': typeof PrivateRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_private/_guild': typeof PrivateGuildRouteRouteWithChildren
  '/_private/dashboard': typeof PrivateDashboardRouteRouteWithChildren
  '/_public/commands': typeof PublicCommandsRoute
  '/_public/status': typeof PublicStatusRoute
  '/_public/': typeof PublicIndexRoute
  '/_private/_guild/guild': typeof PrivateGuildGuildRoute
  '/_private/dashboard/overview': typeof PrivateDashboardOverviewRoute
  '/_public/_auth/logout': typeof PublicAuthLogoutRoute
  '/_public/_auth/redirect': typeof PublicAuthRedirectRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/commands'
    | '/status'
    | '/guild'
    | '/dashboard/overview'
    | '/logout'
    | '/redirect'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/commands'
    | '/status'
    | '/guild'
    | '/dashboard/overview'
    | '/logout'
    | '/redirect'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/_private'
    | '/_public'
    | '/_private/_guild'
    | '/_private/dashboard'
    | '/_public/commands'
    | '/_public/status'
    | '/_public/'
    | '/_private/_guild/guild'
    | '/_private/dashboard/overview'
    | '/_public/_auth/logout'
    | '/_public/_auth/redirect'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PrivateRouteRoute: typeof PrivateRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/status': {
      id: '/_public/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof PublicStatusRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/commands': {
      id: '/_public/commands'
      path: '/commands'
      fullPath: '/commands'
      preLoaderRoute: typeof PublicCommandsRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_private/dashboard': {
      id: '/_private/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PrivateDashboardRouteRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/_guild': {
      id: '/_private/_guild'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateGuildRouteRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/_auth/redirect': {
      id: '/_public/_auth/redirect'
      path: '/redirect'
      fullPath: '/redirect'
      preLoaderRoute: typeof PublicAuthRedirectRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/_auth/logout': {
      id: '/_public/_auth/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof PublicAuthLogoutRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_private/dashboard/overview': {
      id: '/_private/dashboard/overview'
      path: '/overview'
      fullPath: '/dashboard/overview'
      preLoaderRoute: typeof PrivateDashboardOverviewRouteImport
      parentRoute: typeof PrivateDashboardRouteRoute
    }
    '/_private/_guild/guild': {
      id: '/_private/_guild/guild'
      path: '/guild'
      fullPath: '/guild'
      preLoaderRoute: typeof PrivateGuildGuildRouteImport
      parentRoute: typeof PrivateGuildRouteRoute
    }
  }
}

interface PrivateGuildRouteRouteChildren {
  PrivateGuildGuildRoute: typeof PrivateGuildGuildRoute
}

const PrivateGuildRouteRouteChildren: PrivateGuildRouteRouteChildren = {
  PrivateGuildGuildRoute: PrivateGuildGuildRoute,
}

const PrivateGuildRouteRouteWithChildren =
  PrivateGuildRouteRoute._addFileChildren(PrivateGuildRouteRouteChildren)

interface PrivateDashboardRouteRouteChildren {
  PrivateDashboardOverviewRoute: typeof PrivateDashboardOverviewRoute
}

const PrivateDashboardRouteRouteChildren: PrivateDashboardRouteRouteChildren = {
  PrivateDashboardOverviewRoute: PrivateDashboardOverviewRoute,
}

const PrivateDashboardRouteRouteWithChildren =
  PrivateDashboardRouteRoute._addFileChildren(
    PrivateDashboardRouteRouteChildren,
  )

interface PrivateRouteRouteChildren {
  PrivateGuildRouteRoute: typeof PrivateGuildRouteRouteWithChildren
  PrivateDashboardRouteRoute: typeof PrivateDashboardRouteRouteWithChildren
}

const PrivateRouteRouteChildren: PrivateRouteRouteChildren = {
  PrivateGuildRouteRoute: PrivateGuildRouteRouteWithChildren,
  PrivateDashboardRouteRoute: PrivateDashboardRouteRouteWithChildren,
}

const PrivateRouteRouteWithChildren = PrivateRouteRoute._addFileChildren(
  PrivateRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicCommandsRoute: typeof PublicCommandsRoute
  PublicStatusRoute: typeof PublicStatusRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicAuthLogoutRoute: typeof PublicAuthLogoutRoute
  PublicAuthRedirectRoute: typeof PublicAuthRedirectRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicCommandsRoute: PublicCommandsRoute,
  PublicStatusRoute: PublicStatusRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicAuthLogoutRoute: PublicAuthLogoutRoute,
  PublicAuthRedirectRoute: PublicAuthRedirectRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PrivateRouteRoute: PrivateRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
