/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicStatusRouteImport } from './routes/_public/status'
import { Route as PublicCommandsRouteImport } from './routes/_public/commands'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as PublicAuthRedirectRouteImport } from './routes/_public/_auth/redirect'
import { Route as PublicAuthLogoutRouteImport } from './routes/_public/_auth/logout'

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicStatusRoute = PublicStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicCommandsRoute = PublicCommandsRouteImport.update({
  id: '/commands',
  path: '/commands',
  getParentRoute: () => PublicRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicAuthRedirectRoute = PublicAuthRedirectRouteImport.update({
  id: '/_auth/redirect',
  path: '/redirect',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicAuthLogoutRoute = PublicAuthLogoutRouteImport.update({
  id: '/_auth/logout',
  path: '/logout',
  getParentRoute: () => PublicRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/commands': typeof PublicCommandsRoute
  '/status': typeof PublicStatusRoute
  '/logout': typeof PublicAuthLogoutRoute
  '/redirect': typeof PublicAuthRedirectRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/commands': typeof PublicCommandsRoute
  '/status': typeof PublicStatusRoute
  '/': typeof PublicIndexRoute
  '/logout': typeof PublicAuthLogoutRoute
  '/redirect': typeof PublicAuthRedirectRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteRouteWithChildren
  '/_public/commands': typeof PublicCommandsRoute
  '/_public/status': typeof PublicStatusRoute
  '/_public/': typeof PublicIndexRoute
  '/_public/_auth/logout': typeof PublicAuthLogoutRoute
  '/_public/_auth/redirect': typeof PublicAuthRedirectRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/commands'
    | '/status'
    | '/logout'
    | '/redirect'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/commands' | '/status' | '/' | '/logout' | '/redirect' | '/api/auth/$'
  id:
    | '__root__'
    | '/_public'
    | '/_public/commands'
    | '/_public/status'
    | '/_public/'
    | '/_public/_auth/logout'
    | '/_public/_auth/redirect'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/status': {
      id: '/_public/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof PublicStatusRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/commands': {
      id: '/_public/commands'
      path: '/commands'
      fullPath: '/commands'
      preLoaderRoute: typeof PublicCommandsRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/_auth/redirect': {
      id: '/_public/_auth/redirect'
      path: '/redirect'
      fullPath: '/redirect'
      preLoaderRoute: typeof PublicAuthRedirectRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/_auth/logout': {
      id: '/_public/_auth/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof PublicAuthLogoutRouteImport
      parentRoute: typeof PublicRouteRoute
    }
  }
}

interface PublicRouteRouteChildren {
  PublicCommandsRoute: typeof PublicCommandsRoute
  PublicStatusRoute: typeof PublicStatusRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicAuthLogoutRoute: typeof PublicAuthLogoutRoute
  PublicAuthRedirectRoute: typeof PublicAuthRedirectRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicCommandsRoute: PublicCommandsRoute,
  PublicStatusRoute: PublicStatusRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicAuthLogoutRoute: PublicAuthLogoutRoute,
  PublicAuthRedirectRoute: PublicAuthRedirectRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PublicRouteRoute: PublicRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
